version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.34.0
  - dependency-name: "@lapidist/linting"
    versions:
    - 2.102.0
    - 2.68.0
    - 2.82.0
    - 2.89.0
    - 2.96.0
