import type { StoryObj } from '@storybook/react';
import { BaseProps } from '../types';
import { ButtonProps } from './index';
declare const _default: import("@storybook/types").ComponentAnnotations<import("@storybook/react/dist/types-0a347bb9").R, import("@storybook/types").Args>;
export default _default;
export declare const PrimarySmall: StoryObj<BaseProps & ButtonProps>;
export declare const PrimaryMedium: StoryObj<BaseProps & ButtonProps>;
export declare const PrimaryLarge: StoryObj<BaseProps & ButtonProps>;
export declare const PrimaryDisabled: StoryObj<BaseProps & ButtonProps>;
export declare const SecondarySmall: StoryObj<BaseProps & ButtonProps>;
export declare const SecondaryMedium: StoryObj<BaseProps & ButtonProps>;
export declare const SecondaryLarge: StoryObj<BaseProps & ButtonProps>;
export declare const SecondaryDisabled: StoryObj<BaseProps & ButtonProps>;
export declare const TertiarySmall: StoryObj<BaseProps & ButtonProps>;
export declare const TertiaryMedium: StoryObj<BaseProps & ButtonProps>;
export declare const TertiaryLarge: StoryObj<BaseProps & ButtonProps>;
export declare const TertiaryDisabled: StoryObj<BaseProps & ButtonProps>;
export declare const DangerSmall: StoryObj<BaseProps & ButtonProps>;
export declare const DangerMedium: StoryObj<BaseProps & ButtonProps>;
export declare const DangerLarge: StoryObj<BaseProps & ButtonProps>;
export declare const DangerDisabled: StoryObj<BaseProps & ButtonProps>;
export declare const WithIcon: StoryObj<BaseProps & ButtonProps>;
export declare const Block: StoryObj<BaseProps & ButtonProps>;
