import type { StoryObj } from '@storybook/react';
import { BaseProps } from '../types';
import { BoxProps } from './index';
declare const _default: import("@storybook/types").ComponentAnnotations<import("@storybook/react/dist/types-0a347bb9").R, import("@storybook/types").Args>;
export default _default;
export declare const NoGutter: StoryObj<BaseProps & BoxProps>;
export declare const SmallGutter: StoryObj<BaseProps & BoxProps>;
export declare const MediumGutter: StoryObj<BaseProps & BoxProps>;
export declare const LargeGutter: StoryObj<BaseProps & BoxProps>;
export declare const NoElevation: StoryObj<BaseProps & BoxProps>;
export declare const SmallElevation: StoryObj<BaseProps & BoxProps>;
export declare const MediumElevation: StoryObj<BaseProps & BoxProps>;
export declare const LargeElevation: StoryObj<BaseProps & BoxProps>;
export declare const NoRoundness: StoryObj<BaseProps & BoxProps>;
export declare const SmallRoundness: StoryObj<BaseProps & BoxProps>;
export declare const MediumRoundness: StoryObj<BaseProps & BoxProps>;
export declare const LargeRoundness: StoryObj<BaseProps & BoxProps>;
