import type { StoryObj } from '@storybook/react';
import { BaseProps } from '../types';
import { TextProps } from './index';
declare const _default: import("@storybook/types").ComponentAnnotations<import("@storybook/react").ReactRenderer, BaseProps & TextProps>;
export default _default;
export declare const SmallSize: StoryObj<BaseProps & TextProps>;
export declare const MediumSize: StoryObj<BaseProps & TextProps>;
export declare const LargeSize: StoryObj<BaseProps & TextProps>;
export declare const RegularWeight: StoryObj<BaseProps & TextProps>;
export declare const MediumWeight: StoryObj<BaseProps & TextProps>;
export declare const BoldWeight: StoryObj<BaseProps & TextProps>;
export declare const BodyFamily: StoryObj<BaseProps & TextProps>;
export declare const HeadingFamily: StoryObj<BaseProps & TextProps>;
export declare const SerifFamily: StoryObj<BaseProps & TextProps>;
export declare const MonoFamily: StoryObj<BaseProps & TextProps>;
