import type { StoryObj } from '@storybook/react';
import { BaseProps } from '../types';
import { HeadingProps } from './index';
declare const _default: import("@storybook/types").ComponentAnnotations<import("@storybook/react/dist/types-0a347bb9").R, import("@storybook/types").Args>;
export default _default;
export declare const LargeSize: StoryObj<BaseProps & HeadingProps>;
export declare const MediumSize: StoryObj<BaseProps & HeadingProps>;
export declare const SmallSize: StoryObj<BaseProps & HeadingProps>;
export declare const RegularWeight: StoryObj<BaseProps & HeadingProps>;
export declare const MediumWeight: StoryObj<BaseProps & HeadingProps>;
export declare const BoldWeight: StoryObj<BaseProps & HeadingProps>;
export declare const BodyFamily: StoryObj<BaseProps & HeadingProps>;
export declare const HeadingFamily: StoryObj<BaseProps & HeadingProps>;
export declare const SerifFamily: StoryObj<BaseProps & HeadingProps>;
export declare const MonoFamily: StoryObj<BaseProps & HeadingProps>;
