name: Test
on: [pull_request]
jobs:
    release:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 13
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm run test
